version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db

  # Node API service
  api:
    container_name: api_container
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      MONGODB_URL: mongodb://mongo_db:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.10.0
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}